# Generated by Django 3.2.5 on 2021-07-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_college_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='div',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default=0, max_length=225),
            preserve_default=False,
        ),
    ]
